### PR TITLE
Add checkbox to use pre-trained weights

### PR DESCRIPTION
**Pull request by dstansby**
I accidentally implemented this yesterday for my own testing before realising it was part of fixing https://github.com/brainglobe/cellfinder-napari/issues/56!

### CODE REVIEW

**Review by alessandrofelder — CHANGES_REQUESTED** [review]
I'd suggest we have `use_pre_trained_weights == True` by default (because that behaviour was default before this PR) and leave the text box empty by default?

These can be separate issues (I'll check they exist and create them otherwise):
* greying out the text box if `use_pre_trained_weights` is `True`
* error handling and user feedback if the user passes a non-valid `trained_model` 

 Otherwise, looks good 👍

**Comment by dstansby** [comment]
> I'd suggest we have `use_pre_trained_weights == True` by default

Done

> and leave the text box empty by default?

I'm not sure how to do this - `magicgui` seems to use `Path.home()` as the deafult value for Path-like attributes.

**Comment by alessandrofelder** [comment]
I suspect it's not `magicgui` but rather the fact that the widget values persist that makes you think that?
At least for me, I can set `trained_model: Optional[Path] = Path("/")` in the dataclass and, after hitting reset defaults that shows "C:/"?

**Comment by alessandrofelder** [comment]
But you're right, it doesn't look like `pathlib` has a sensible "NonePath" or something like that. Not sure whether `Path("/")` or `Path.home()` is better as default there?

**Review by alessandrofelder — APPROVED** [review]
No strong opinion about `Path.home()` or `Path("/") in that case, but see my comments and tell me what you think :) Thanks!

**Comment by paddyroddy** [comment]
> I think I'm on the side of leaving it as `Path.home()` and @paddyroddy fixing or changing it when he tackles #56.
> 
> (p.s. sorry for opening this when you were assigned to that issue @paddyroddy, still finding my feet a bit!)

no problem, I hadn't had time to get around to it yet

**Pull request merged**
